name: Matt Hadley Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.512629660544917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414142'
    - '#00aeef'
    - '#000000'
    - '#80ffff'
    - '#0000ff'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
